# Generated by Django 5.0.3 on 2024-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0002_alter_space_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
